#服务暴露的端口
server:
  port: 8001
#注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
#注册时的服务名
spring:
  application:
    name: employee-provider
spring:
  cloud:
    config:
      name: application-plat #github上面名称
      profile: dve #环境
      label: master #分支
      uri: http://127.0.0.1:10001 #配置服务器